/*
******************************************************************************
File:     main.cpp
Info:     Generated by Atollic TrueSTUDIO(R) 9.0.0   2019-05-14

The MIT License (MIT)
Copyright (c) 2018 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f4xx.h"
#include "stm32f4_discovery.h"

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
volatile int ticks=0;
extern "C" void SysTicks_Handler(){
	ticks++;
}
void delay_ms(int interval){
	int temp=ticks+interval;
	while (ticks<temp);
}
// 3 4 6 5
int main(void)
{
	RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOD, ENABLE); //habilitando o periférico
	GPIO_InitTypeDef a,b,c,d;    // inicializando os objetos de config

	a.GPIO_Mode=GPIO_Mode_OUT;    // configurando o 'a'
	a.GPIO_OType=GPIO_OType_PP;
	a.GPIO_PuPd=GPIO_PuPd_NOPULL;
	a.GPIO_Speed=GPIO_Speed_2MHz;

	d=c=b=a;                      // replicando as config de a nos demais

	a.GPIO_Pin=GPIO_Pin_13;		  // dando a cada um o pino correspondente
	b.GPIO_Pin=GPIO_Pin_12;
	c.GPIO_Pin=GPIO_Pin_15;
	d.GPIO_Pin=GPIO_Pin_14;


	GPIO_Init(GPIOD, &a);     // inicializando os pinos
	GPIO_Init(GPIOD, &b);
	GPIO_Init(GPIOD, &c);
	GPIO_Init(GPIOD, &d);

	SysTick_Config(168000);

	while(1){
		GPIO_SetBits(GPIOD, GPIO_Pin_13);
		delay_ms(100);
		GPIO_ResetBits(GPIOD, GPIO_Pin_13);

		GPIO_SetBits(GPIOD, GPIO_Pin_12);
		delay_ms(100);
		GPIO_ResetBits(GPIOD, GPIO_Pin_12);

		GPIO_SetBits(GPIOD, GPIO_Pin_15);
		delay_ms(100);
		GPIO_ResetBits(GPIOD, GPIO_Pin_15);

		GPIO_SetBits(GPIOD, GPIO_Pin_14);
		delay_ms(100);
		GPIO_ResetBits(GPIOD, GPIO_Pin_14);
	}

}

extern "C" void EVAL_AUDIO_TransferComplete_CallBack(uint32_t pBuffer, uint32_t Size){
  /* TODO, implement your code here */
  return;
}

/*
 * Callback used by stm324xg_eval_audio_codec.c.
 * Refer to stm324xg_eval_audio_codec.h for more info.
 */
extern "C" uint16_t EVAL_AUDIO_GetSampleCallBack(void){
  /* TODO, implement your code here */
  return -1;
}
